# Generated by Django 5.1.1 on 2024-09-22 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StorageSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('S', 'Standard'), ('R', 'Raised'), ('H', 'High')], default='L', max_length=2)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='(xxxxx)x.xx In sqr. meters m^2', max_digits=8, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_spaces.storagespacetype')),
            ],
        ),
    ]
