# Generated by Django 5.1.1 on 2024-09-22 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_employee'),
        ('storage_spaces', '0001_storage_space_and_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_unique', models.BooleanField(default=False, help_text='Mark as unique if this Role has to be unique within the storage space employees.')),
            ],
        ),
        migrations.CreateModel(
            name='Accountable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_from', models.TimeField()),
                ('work_until', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('storage_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_spaces.storagespace')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_spaces.accountabletype')),
            ],
        ),
    ]
