# Generated by Django 5.1.1 on 2024-09-23 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_employee'),
        ('storage_spaces', '0002_accountable_type_and_accountable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountabletype',
            name='prio_idx',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='accountable',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountables', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='accountable',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountables', to='storage_spaces.accountabletype'),
        ),
        migrations.AlterField(
            model_name='accountable',
            name='storage_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountables', to='storage_spaces.storagespace'),
        ),
        migrations.AlterField(
            model_name='storagespace',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_spaces', to='storage_spaces.storagespacetype'),
        ),
    ]
