# Generated by Django 5.1.1 on 2024-09-23 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_activity_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action_time',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='status',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='coordinator',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='employee',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='item',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='operation_type',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='storage_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='storage_to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
