# Generated by Django 5.1.1 on 2024-09-22 08:13

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_inventory_class_and_item'),
        ('storage_spaces', '0002_accountable_type_and_accountable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AddField(
            model_name='item',
            name='storage_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storage_spaces.storagespace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity, for space calculation (qtty * size)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.DecimalField(decimal_places=2, help_text='(xxx)x.xx In sqr. meters m^2. Single package size (eg. 1 box)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size_total',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('size')), output_field=models.DecimalField(decimal_places=2, max_digits=8)),
        ),
    ]
