# Generated by Django 5.1.1 on 2024-09-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_items_storage_space_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inventory_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.class'),
        ),
    ]
