# Generated by Django 5.1.1 on 2024-09-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Quantity, for space calculation (qtty * size)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(xxx)x.xx In sqr. meters m^2. Single package size (eg. 1 box)', max_digits=6, null=True),
        ),
    ]
